### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by ErwanSC** [jasonmcintosh/rabbitmq-zabbix#106]
Hi,

I was looking for rabbitmq monitoring and your solution seems light but it's KO for me.
When i run api.py, i got a SSL WRONG VERSION NUMBER

My command : 
```./api.py --hostname=127.0.0.1 --username=$USERNAME --password=$PASSWORD --check=server --metric=rabbitmq_version --node="$NODE" --filters='{"durable": true}' --conf=$CONF  --loglevel=${LOGLEVEL} --logfile=${LOGFILE} --port=15672 --protocol=HTTPS```

And this is the result :
```Traceback (most recent call last):
  File "./api.py", line 299, in <module>
    main()
  File "./api.py", line 296, in main
    print api.check_server(options.metric, api.host_name)
  File "./api.py", line 231, in check_server
    nodeInfo = self.call_api('nodes')
  File "./api.py", line 39, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:726)>```

Any idea ?
Thanks.

**Comment by ErwanSC** [comment]
Wrong protocol, i had to use HTTP instead of HTTPS.

My bad.
