### ISSUE TITLE
part of items won't work

### ISSUE THREAD

**Issue by lastessa** [jasonmcintosh/rabbitmq-zabbix#17]
Hi, testing you template.
In  /var/log/zabbix/rabbitmq_zabbix.log
2015-03-06 15:49:58,347 WARNING: 
2015-03-06 15:50:22,478 WARNING: Sending failed. Use option -vv for more detailed output.

2015-03-06 15:50:22,478 WARNING: 
2015-03-06 15:50:28,533 WARNING: Sending failed. Use option -vv for more detailed output.

2015-03-06 15:50:28,533 WARNING: 
2015-03-06 15:50:28,849 WARNING: Sending failed. Use option -vv for more detailed output.

2015-03-06 15:50:28,849 WARNING:

and latest data for items such as:

rabbitmq[{#NODENAME},ab,queue_msg_unackd,celery@celery1.worker5.celery.pidbox]
60	3	90	Zabbix agent	-	-	-	Graph	
	
RabbitMQ queue_msg_unackd celery@celery6.worker6.celery.pidbox {#NODENAME} (ab)
rabbitmq[{#NODENAME},ab,queue_msg_unackd,celery@celery6.worker6.celery.pidbox]
60	3	90	Zabbix agent	-	-	-	Graph	
	
RabbitMQ queue_msg_unackd celery@w1.local.celery.pidbox {#NODENAME} (ab)
rabbitmq[{#NODENAME},ab,queue_msg_unackd,celery@w1.local.celery.pidbox]
60	3	90	Zabbix agent	-	-	-	Graph	
	
...not collected

**Comment by jasonmcintosh** [comment]
Hrmmm, at a guess, it's not liking the @ in the queue names...  I'll need to dig into this but I might need to URL encode or escape the queue names.

**Comment by jasonmcintosh** [comment]
Near as I can tell, this is actually working just fine with @ and ''s in the request.  Specifically I created the queue "Test Queue @Bob's Uncle".  Auto discovery picked it up, created a queue locally just fine.  Debug on log files shows:

2015-03-11 15:15:09,974 DEBUG: Started trying to process data
2015-03-11 15:15:09,974 DEBUG: Issue a rabbit API call to get data on overview
2015-03-11 15:15:10,064 DEBUG: Started trying to process data
2015-03-11 15:15:10,065 DEBUG: Issue a rabbit API call to get data on overview
2015-03-11 15:15:38,164 DEBUG: Started trying to process data
2015-03-11 15:15:38,165 DEBUG: Issue a rabbit API call to get data on nodes
2015-03-11 15:15:39,259 DEBUG: Started trying to process data
2015-03-11 15:15:39,260 DEBUG: Issue a rabbit API call to get data on queues
2015-03-11 15:15:39,270 DEBUG: Filtering out by [{}]
2015-03-11 15:15:39,270 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_memory,Test Queue @Bob's Uncle]" 14016
2015-03-11 15:15:39,270 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_messages,Test Queue @Bob's Uncle]" 0
2015-03-11 15:15:39,270 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_messages_unacknowledged,Test Queue @Bob's Uncle]" 0
2015-03-11 15:15:39,270 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_consumers,Test Queue @Bob's Uncle]" 0
2015-03-11 15:15:39,271 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_message_stats_deliver_get,Test Queue @Bob's Uncle]" 0
2015-03-11 15:15:39,271 DEBUG: SENDER_DATA: - "rabbitmq[/,queue_message_stats_publish,Test Queue @Bob's Uncle]" 0
2015-03-11 15:15:39,277 DEBUG: Finished sending data
2015-03-11 15:15:39,277 INFO: Found return code of 0
2015-03-11 15:15:39,277 DEBUG:
2015-03-11 15:15:39,278 DEBUG: info from server: "processed: 6; failed: 0; total: 6; seconds spent: 0.000091"
sent: 6; skipped: 0; total: 6


If you want to get me more details on your stuff, I can look into this more, but I'm not seeing any issues with the queues you've got named up there, but I'm not 100% sure what I'm seeing.

**Comment by lastessa** [comment]
Hi, Jason.
What kind of info do you need?
The problem still persist by my side.

Îòïðàâëåíî ñ iPhone

**Comment by jasonmcintosh** [comment]
SO looking at what isn't working:

> RabbitMQ queue_msg_unackd celery@celery6.worker6.celery.pidbox {#NODENAME} (ab)
> rabbitmq[{#NODENAME},ab,queue_msg_unackd,celery@celery6.worker6.celery.pidbox]
> 60 3 90 Zabbix agent - - - Graph

It ALMOST appears like the template or something else is different on your system.  Here's a copy of the line from the zabbix I'm using:

> RabbitMQ queue_consumers on vhost /, queue Test Queue @Bob's Uncle	12 Mar 2015 08:51:07	0	-	Graph

A screen shot would also be helpful as your output doesn't seem to match what I've got on Zabbix 2.2.  At that point what version of Zabbix are you running?  What version of the sender?  I've tested with 2.2+ though I believe 2.0 will work as well.  What version of RabbitMQ are you running?  You can try a few things like disabling the delete of the log file and running the various pages by hand, e.g. 
<code>
sh /etc/zabbix/scripts/rabbitmq/rabbitmq-status.sh queues
</code>
If you remove the os.unlink that SHOULD I believe leave the old tmp file in place which you can look at the contents - a few samples of that would also be handy.

**Comment by lastessa** [comment]
>./rabbitmq-status.sh queues
Traceback (most recent call last):
  File "./api.py", line 210, in <module>
    main()
  File "./api.py", line 197, in main
    print api.check_queue(filters)
  File "./api.py", line 81, in check_queue
    for queue in self.call_api('queues'):
  File "./api.py", line 37, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 880, in http_error_401
    url, req, headers)
  File "/usr/lib64/python2.6/urllib2.py", line 858, in http_error_auth_reqed
    return self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib64/python2.6/urllib2.py", line 868, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
Exit 1

but:
./list_rabbit_queues.sh 
{"data": [{"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.backup"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.base_resize"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.blur"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.copy"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.crop"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.delete"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.resize"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.resize_proc"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.rotate"}, {"{#VHOSTNAME}": "/", "{#QUEUENAME}": "a1.watermark"}]}

so .rab.auth is ok.

>zabbix_agentd --version
Zabbix Agent (daemon) v2.2.1 (revision 40808) (09 December 2013)
Compilation time: Jan 28 2014 16:48:50

>zabbix_server --version
Zabbix server v2.4.3 (revision 51175) (15 December 2014)
Compilation time: Mar  5 2015 10:44:28

RabbitMQ 3.4.4, Erlang R14B04

**Comment by lastessa** [comment]
PS: i'm trying test on another rabbitmq instance.

**Comment by jasonmcintosh** [comment]
K I'm on rabbitmq 3.4.4 myself for these tests, so that shouldn't be an issue.  Off hand, it appears something is odd on your server.  You're getting an authorization error trying to get queue data, yet the list-queues command succeeds with the same user/password - something is screwy.  On line 35 or so, you can add a 
<code>
logging.debug("Username:{0}, Password:{1}, Call:{2}".format(self.user_name, self.password, self.path))
</code>
This should output the results of any calls to the log file.  A list_rabbit_queues and a rabbitmq-status.sh queues should BOTH generate a line that's identical.  If they're not, somehow your status sh file isn't able to access that .rab.auth or similar.  Again that's a guess.  You can also try calling api.py directly:
<code>
./api.py --hostname=<name-in-zabbix> --username=guest --password=guest --check=queues --conf=/etc/zabbix/zabbix_agentd.conf
</code>

**Comment by jasonmcintosh** [comment]
Any updates?  If not I'll close this in another day
