### ISSUE TITLE
check_aliveness check isn't passing

### ISSUE THREAD

**Issue by dene14** [jasonmcintosh/rabbitmq-zabbix#27]
Hello Jason!

I wonder if I'm doing something wrong... Can't pass aliveness check however list queues passing well:
\# python api.py --username=admin --password=mypass --check=list_queues
{"data": []}

\# python api.py --username=admin --password=mypass --check=check_aliveness
Traceback (most recent call last):
  File "rabbitmq-api.py", line 209, in <module>
    main()
  File "api.py", line 198, in main
    print api.check_aliveness()
  File "api.py", line 137, in check_aliveness
    return self.call_api('aliveness-test/%2f')['status']
  File "api.py", line 36, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

P.S. I'm using last revision from master.

**Comment by dene14** [comment]
funny thing that check passes when I use guest user and hostname 'localhost' :)

**Comment by jasonmcintosh** [comment]
Yep - closing this issue.  Have to have the right username/password ;)

"urllib2.HTTPError: HTTP Error 401: Unauthorized"
