### ISSUE TITLE
Received value [Traceback (most recent call last)

### ISSUE THREAD

**Issue by kommeht3d** [jasonmcintosh/rabbitmq-zabbix#69]
hello.
I have error in zabbix . key (rabbitmq[server,disk_free])

Received value [Usage: api.py [options]api.py: error: option --port: invalid integer value: ''] is not suitable for value type [

and key 	rabbitmq[server,mem_limit]
I have error

Received value [Traceback (most recent call last): File "./api.py", line 277, in <module> main() File "./api.py", line 239,

**Comment by kommeht3d** [comment]
I added the variables to .rab.auth

PORT=15672
HOSTNAME=localhost

now, zabbix get all the values from rabbitmq

but, zabbix-agent not run automatic, and if I`ll run it manual, in the log file zabbix-agent write error

 1557:20170511:163718.254 the system time has been pushed back, adjusting active check schedule
  1557:20170511:163848.423 active check "rabbitmq.discovery_queue" is not supported: Unsupported item key.

zabbix server displays the correct data from rabbitmq (all item is working) , but have a error 
Get value from agent failed: cannot connect to [[172.18.12.60]:10050]: [111] Connection refused

please, help

**Comment by kommeht3d** [comment]
Figured out:)

closed
