### ISSUE TITLE
No data is seen on Zabbix

### ISSUE THREAD

**Issue by asksubbu** [jasonmcintosh/rabbitmq-zabbix#80]
Not able to see any data on Zabbix, only following error is shown, however when i execute the scripts locally on the rabbit mq server, it does work, what could be the reason?

Changed log level to debug and do not see any error.

Traceback (most recent call last):
  File "./api.py", line 285, in <module>
    main()
  File "./api.py", line 280, in main
    print api.check_server(options.metric, options.node)
  File "./api.py", line 214, in check_server
    return self.call_api('overview').get('rabbitmq_version', 'None')
  File "./api.py", line 37, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 13] Permission denied>

**Comment by jasonmcintosh** [comment]
"urlopen error [Errno 13] Permission denied" - this means likely your user doesn't have permissions on the rabbitmq server you're connecting to.

**Comment by jasonmcintosh** [comment]
Second piece of this - it's likely your ZABBIX user which doesn't have permissions or can't read a config file or similar.  I usually su - to that user and run in that way.
